### ISSUE TITLE
Remove a Competitor from a Competition

### ISSUE THREAD

**Issue by Sch3lp** [SoftwareSandbox/effit-challenge#27]
**Why this feature**
When a user made a mistake of adding some name to the competitor list, there's no way of correcting that mistake aside from starting a new Competition...

**Tasks**

* [x] Redesign the way competitors of a Competition are displayed (render as `chip`s?)
* [x] Add a REST API call to remove a competitor from a Competition.
* [x] When deleting a Competition, all its Competitors should also get removed (orphan removal)
* [ ] ~~Scenario Test~~

**Comment by Sch3lp** [comment]
Left ScenarioTest for issue #23
