### ISSUE TITLE
Edit a freshly created Challenge

### ISSUE THREAD

**Issue by Sch3lp** [SoftwareSandbox/effit-challenge#29]
**Why this feature**
I just created a Challenge, but after pressing Submit, I noticed there was typo and now there's no way of fixing it. I cannot even delete the Challenge, so it'll just take up space when selecting challenges for a Competition...

**Tasks**

* [ ] Make a Challenge clickable from the Challenges Overview, should navigate to `challenge/123/edit`
* [ ] New REST API Endpoint to update a Challenges name, points, etc.
* [ ] Integration Test that creates a challenge, creates a competition using it, and then modifies the challenge. The Competition using the challenge should not be effected (challenge at coupling time should not be effected)
