### ISSUE TITLE
Manually start a competition

### ISSUE THREAD

**Issue by Sch3lp** [SoftwareSandbox/effit-challenge#38]
**Tasks**
* [x] Add a flag marking a competition as started or not
* [x] Add button to mark competition as started (toggle button)
* [ ] Don't allow completing challenges when a competition is not started yet (refactor, move `controller.completeChallenge` to `competition`)
* [x] Think about whether or not the `unstart` feature is a good idea.
* [x] Add notification when a Competition was started.
* [x] _Move_ `unstart` to an undo button in the competition started notification.

**Why this feature**
This is actually solves the _malicious competitor_ issue in a different way. In a way we don't need security, or the distinction between an admin and a regular participant anymore.

The idea is that modifications to the competitors of a competition are blocked after a competition has been started.
