### ISSUE TITLE
Show challenges of an unstarted Competition to be able to hype your friend group.

### ISSUE THREAD

**Issue by Sch3lp** [SoftwareSandbox/effit-challenge#46]
**Why this feature**
As a competition organizer I currently can't relay the challenges of a competition to my friend group and I want to get them hyped up by showing them the challenges I have prepared for them.

**Tasks**

* [x] Move competitors + adding them underneath start competition button
* [x] Show challenges table when competition not yet started
* [x] Show Scoreboard when competition has been started
