### ISSUE TITLE
Decide what the actual flow of creating a competition should be

### ISSUE THREAD

**Issue by Sch3lp** [SoftwareSandbox/effit-challenge#57]
**Why this feature**
We now have multiple ways of creating a competition:

* You either start creating an entirely new competition, and create challenges for that competition on the fly.
* Or, you start from an already existing competition (and select _host again_), but that doesn't even include the challenges that were part of that competition.

Right now we're in some kind of middle ground where you can still select the challenges from **all** challenges of **all** competitions, but it's kind of useless feature. The idea of that last feature is so you can get inspired by other competitions' challenges.

Since the app's main purpose is to be ready for Snowcase 2020, we'll go with the proper implementation of _Host Again_, and immediately select all of the challenges of that competition you want to host again to be included in the _newly_ aka _hosted again_ competition.
And get rid of the challenge selection table.

**Tasks**

* [x] Remove selection of challenges/challenge table
* [x] Include challenges of the competition to host from
* [ ] ~~Integration Tests necessary?~~
